config/routes.rb
Rails.application.routes.draw do
  get 'home/about' => 'homes#about'
  devise_for :users
  root to: 'homes#top'
  resources :users, only: [:show,:edit,:index,:update]
  resources :books do
    resource :favorites, only: [:destroy,:create]
  end
  resource :relationships, only: [:create, :destroy]
#resources :users, only: [:edit,:]
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'

  validates :followed_id, presence: true
  validates :follower_id, presence: true
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :set_user

  def create
    following = current_user.follow(@user)
    if following.save
      flash[:success] = 'ユーザーをフォローしました'
      redirect_to user_path(@user.id)
    else
      flash.now[:alert] = 'ユーザーのフォローに失敗しました'
      redirect_to user_path(@user.id)
    end
  end

  def destroy
    following = current_user.unfollow(@user)
    if following.destroy
      flash[:success] = 'ユーザーのフォローを解除しました'
      redirect_to user_path(@user.id)
    else
      flash.now[:alert] = 'ユーザーのフォロー解除に失敗しました'
      redirect_to user_path(@user.id)
    end
  end

  private
    def  set_user
    @user = User.find(params[:follow_id])
    end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_follow_button.html.erb
<% unless current_user == user %>
  <% if current_user.following?(user) %>
    <%= form_with(url: relationships_path, method: :delete, local: true) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
    <% end %>
  <% else %>
    <%= form_with(url: relationships_path, method: :post, local: true) do |f| %>
      <%= hidden_field_tag :follow_id, user.id %>
      <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
    <% end %>
  <% end %>
<% end %>