config/routes.rb
Rails.application.routes.draw do
  get 'home/about' => 'homes#about'
  devise_for :users
  root to: 'homes#top'
  resources :users, only: [:show,:edit,:index,:update]
  resources :books do
    resource :favorites, only: [:destroy,:create]
  end
  resource :relationships, only: [:create, :destroy]
#resources :users, only: [:edit,:]
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
           has_many :favorites,dependent: :destroy
           attachment :profile_image
           has_many :books, dependent: :destroy
           has_many :follower, class_name: 'Relationship', foreign_key: 'follower_id',dependent: :destroy
           has_many :followed, class_name: 'Relationship', foreign_key: 'followed_id',dependent: :destroy
           has_many :followers, through: :followed, source: :follower
           has_many :followings, through: :follower, source: :followed
        def follow(other_user)
            unless self == other_user
            self.follower.find_or_create_by(followed_id: other_user.id)
            end
        end

        def unfollow(other_user)
            follower = self.follower.find_by(followed_id: other_user.id)
            follower.destroy if follower
        end

        def following?(other_user)
            followings.include?(other_user)
        end
            validates :name, presence: true
            validates :name, length: { minimum: 2 }
            validates :name, length: { maximum: 20 }
            validates :introduction, length: { maximum: 50 }
            validates :name, uniqueness: true
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  
  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!
before_action :ensure_correct_user,only: [:edit, :update]
  def show
       @user = User.find(params[:id])
       @books=@user.books.all
       @book=Book.new
  end

  def edit
       @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
     if @user.update(user_params)
      flash[:notice] =  "You have updated user successfully."
      redirect_to user_path(@user)
     else
      render :edit
     end
  end

  def index
   @users = User.all
   @book=Book.new
   @user=current_user
  end

  private
  # ストロングパラメータ
  def user_params
     params.require(:user).permit(:profile_image, :name, :introduction)
  end
  
 def ensure_correct_user
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user)
    end
 end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <% if @user.errors.any? %>
  　　<div class = "alert">
      <h3><%= pluralize(@user.errors.count, "error") %> prohibited this obj from being saved:</h3>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            <% end %>
       <h2>User info</h2>
       <%= form_with model:@user, local:true do |f| %>
      <div class="form-group">
       <label for="inputName">Name</label>
        <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
      </div>
      <div class="form-group">
      <label for="inputImage">Image</label>
         <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
      </div>
      <div class="form-group">
        <label for="user_introduction">Introduction</label>
       <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:""%>
      </div>
           <%= f.submit "Update User" %>
        <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <div>
        <h2>User info</h2>
        <p><%= attachment_image_tag @user, :profile_image, :fill, 75, 75, fallback: "no_image.jpg" %></p>
        <p>name：<%= current_user.name %></p>
        <p>introduction：<%= current_user.introduction %></p>
      </div>

        <p><%= link_to "", edit_user_path(@user),class: "btn btn-outline-secondary btn-block fas fa-user-cog" %></p>

      <h1>New book</h1>
      <!-- form_with部分 -->
      <%= form_with model: @book, local:true do |f| %>
        <h4>Title</h4>
        <%= f.text_field :title %>
        <h4>Opinion</h4>
        <%= f.text_area :body %>
        <%= f.submit 'Create Book' %>
      <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class='table table-hover table-inverse'>
       <thead>
         <tr>
           <th>
             image
           </th>
           <th>
             name
           </th>
           <th calspan="3">
           </th>
       </thead>
       <tbody>
          <% @users.each do |user| %>
        <tr>
          <td> <%= attachment_image_tag user, :profile_image, :fill, 75, 75, fallback: "no_image.jpg" %>
          </td>
          <td><%= user.name %></td>
          <td><%= user.id %></td>
         <td><%= render partial: "relationships/follow_button", locals: { user: user} %></td>
          <td> <%=link_to "Show", user_path(user) %></td>
        </tr>
          <% end %>
       </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <div>
          <h2>User info</h2>
          <p><%= attachment_image_tag @user, :profile_image, :fill, 75, 75, fallback: "no_image.jpg" %></p>
          <p>name：<%= @user.name %></p>
          <p>introduction：<%= @user.introduction %></p>
          <%= render partial: "relationships/follow_button", locals: { user: @user} %>
        </div>
          <p><%= link_to "", edit_user_path(@user),class: "btn btn-outline-secondary btn-block fas fa-user-cog" %></p>
        <h1>New book</h1>
        <!-- form_with部分 -->
        <%= form_with model: @book, local:true do |f| %>
          <h4>Title</h4>
          <%= f.text_field :title %>
          <h4>Opinion</h4>
          <%= f.text_area :body %>
          <%= f.submit 'Create Book' %>
        <% end %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @books.each do |book| %>
              <tr>
                <td>
                  <%= link_to user_path(book.user) do %>
                  <%= attachment_image_tag @user, :profile_image, :fill, 75, 75, fallback: "no_image.jpg" %>
                 <% end %>
                </td>
                <td><%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
                </td>
                <td> <%= book.body %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>