config/routes.rb
Rails.application.routes.draw do
  get 'home/about' => 'homes#about'
  devise_for :users
  root to: 'homes#top'
  resources :users, only: [:show,:edit,:index,:update]
  resources :books do
    resource :favorites, only: [:destroy,:create]
  end
  resource :relationships, only: [:create, :destroy]
#resources :users, only: [:edit,:]
# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
     validates :title, presence: true
     validates :body, presence: true
     validates :body, length: { maximum: 200 }
     has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user,only: [:edit, :update]
  def create
    @book =  Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book)
    else
      @books = Book.all
      @user =  current_user
      render :index
    end

  end

  def index
     @books = Book.all
     @book = Book.new
     @user=current_user
  end

  def show
     @book = Book.find(params[:id])
     @user = @book.user
     @books = Book.new
  end

  def edit
    @book = Book.find(params[:id])
    @user = current_user

  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book)
    else
      @books = Book.all
      @user =  current_user
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end


  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
  def ensure_correct_user
    @book = Book.find(params[:id])
    if @book.user.id != current_user.id
      redirect_to books_path
    end
  end


end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if @book.errors.any? %>
  　　<div class = "alert">
      <h3><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
      <% end %>
      <%= form_with model: @book, local:true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title %>
        </div>
        <div>
         <label for="book_opinion">Opinion</label>
          <%= f.text_area :body %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book' %>
        </div>
        <div>
          <%= link_to "Show",book_path(@book) %>
          <%= link_to "Back",books_path %>
        </div>
      <% end %>
   </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <% if @book.errors.any? %>
  　　<div class = "alert">
      <h3><%= pluralize(@book.errors.count, "error") %> prohibited this obj from being saved:</h3>
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
       </div>
<% end %>
      <div>
        <h2>User info</h2>
        <p><%= attachment_image_tag @user, :profile_image, :fill, 75, 75, fallback: "no_image.jpg" %></p>
        <p>name：<%= current_user.name %></p>
        <p>introduction：<%= current_user.introduction %></p>
      </div>

          <p><%= link_to "", edit_user_path(@user),class: "btn btn-outline-secondary btn-block fas fa-user-cog" %></p>


        <h1>New book</h1>
        <!-- form_with部分 -->
        <%= form_with model: @book, local:true do |f| %>
          <h4>Title</h4>
          <%= f.text_field :title %>
          <h4>Opinion</h4>
          <%= f.text_area :body %>
          <%= f.submit 'Create Book' %>
          <% end %>
     </div>
     <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user)do %>
                 <%= attachment_image_tag book.user, :profile_image, :fill, 75, 75, fallback: 'no_image.jpg' %>
                 <% end %>
              </td>
              <td>
                <%=link_to book.title, book_path(book) %>
              </td>
              <td>
                 <%= book.body %>
              </td>
              <% if book.favorited_by?(current_user) %>
              <td>
                <%= link_to book_favorites_path(book), method: :delete do %>
                  ♥<%= book.favorites.count %> いいね
                <% end %>
              </td>
            <% else %>
              <td>
                <%= link_to book_favorites_path(book), method: :post do %>
                  ♡<%= book.favorites.count %> いいね
                <% end %>
              </td>
            <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
     </div>
    </div>
  </div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <div>
        <h2>User info</h2>
        <p><%= attachment_image_tag @user, :profile_image, :fill, 75, 75, fallback: "no_image.jpg" %></p>
        <p>name：<%= @user.name %></p>
        <p>introduction：<%= @user.introduction %></p>
          <%= render partial: "relationships/follow_button", locals: { user: @user } %>
      </div>
            <p><%= link_to "", edit_user_path(@user),class: "btn btn-outline-secondary btn-block fas fa-user-cog" %></p>
            <h1>New book</h1>
            <!-- form_with部分 -->
            <%= form_with model: @books, local:true do |f| %>
              <h4>Title</h4>
              <%= f.text_field :title %>
              <h4>Opinion</h4>
              <%= f.text_area :body %>
              <%= f.submit 'Create Book' %>
            <% end %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
       <table class='table table-hover table-inverse'>
         <thead>
           <tr>
           </tr>
         </thead>
         <tbody>
           <tr>
             <td>
               <%= link_to user_path(@book.user)do %>
               <%= attachment_image_tag @user, :profile_image, :fill, 10, 10, fallback: "no_image.jpg" %>
               <%= @book.user.name %>
               <% end %>
             </td>
             <td><%= link_to @book.title,book_path(@book.id)  %></td>
             <td> <%= @book.body %></td>
             <% if @book.user == current_user %>
             <td> <%= link_to "Edit",edit_book_path(@book) %></td>
             <td> <%= link_to "Destroy",book_path(@book.id), method: :delete, "data-confirm" => "本当に消しますか？" %>
             </td>
             <% end %>
           </tr>
         </tbody>
      　</table>
    </div>
  </div>
</div>